---
title: "Simple similiarity in CHILDES"
author: "Dan Yurovsky & Claire Bergey"
date: "`r Sys.Date()`"
output: 
  html_document:
  toc: false
number_sections: false
theme: lumen
toc_float: false
code_folding: hide
---
  
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(knitr)
library(tidyverse)
library(tidytext)
library(childesr)
library(stringr)
library(lsa)

opts_chunk$set(echo = TRUE, message = FALSE, warning = FALSE, 
               error = FALSE, cache = TRUE, tidy = FALSE)

theme_set(theme_classic(base_size = 14))

```


```{r co-occurrence}
tokens <-  c("boat", "sea", "river", "bee", "ant", "honey", 
             "cow", "pig", "milk", "crib", "baby", "bed", "sleep")

types <- get_types(type = "*")


word_counts <- types %>%
  filter(!gloss %in% c("xxx", "yyy", "")) %>%
  group_by(gloss) %>%
  summarise(count = sum(count)) %>%
  filter(!str_detect(gloss, "[:punct:]"))

top_words <- word_counts %>%
  arrange(desc(count)) %>%
  slice(200:205) %>%
  pull(gloss) 

model_words <- unique(c(tokens, top_words))
  
example_tokens <- get_tokens(token = model_words)

co_occurrs <- example_tokens %>%
  filter(!is.na(target_child_age)) %>%
  filter(!str_detect(gloss, "[:punct:]")) %>%
  arrange(target_child_age, transcript_id, utterance_id) %>%
  mutate(token = tolower(gloss)) %>%
  group_by(utterance_id, token) %>%
  summarise(n = n()) %>%
  spread(token, n, fill = 0)  %>%
  ungroup() 

counts <- function(word, rows) {
  
  word <- enquo(word)

  co_occurrs %>%
    slice(rows) %>%
    filter((!!word) > 0) %>%
    select(-utterance_id) %>%
    summarise_all(sum) %>%
    mutate(target = as.character(word)[2])
}


sections <- seq(25000, 250000, 25000)

co_occur_subset <- function(max_row) {
  map(model_words, 
      function(token) counts(!!as.symbol(token), 1:max_row)) %>%
    bind_rows() %>%
    mutate(max_row = max_row)
}


cumulative_co_occurs <- map(sections,  co_occur_subset) %>%
  bind_rows() %>%
  gather(word, count, model_words) %>%
  group_by(max_row, target)

# total_occurs <- cumulative_co_occurs %>%
#   filter(word == target) %>%
#   rename(occurs = count) %>%
#   select(-word)
#  
cosine_sims <- function(df) {
  df_matrix <- df %>%
    select(-word, -max_row) %>%
    as.matrix()
  
  cosine(df_matrix) %>%
    as_data_frame() %>%
    mutate(word = names(.)) %>%
    gather(target, similarity, -word) %>%
    mutate(max_row = unique(df$max_row))
    
}


cosine_sims <- cumulative_co_occurs %>%
  arrange(max_row, target, word) %>%
  filter(target %in% tokens) %>%
  spread(target, count) %>%
  ungroup() %>%
  split(.$max_row) %>%
  map(cosine_sims) %>%
  bind_rows()

token_cosines <- cosine_sims %>%
  filter(target %in% tokens) %>%
  filter(word != target)

ggplot(filter(token_cosines, word != target, target == "bee", 
              word %in% c("ant", "honey")), 
       aes(x = max_row, y= similarity, color = word)) + 
  facet_wrap(~target) + 
  geom_line() 

direct_co_occurs <- cumulative_co_occurs%>%
  filter(target %in% tokens,
         word %in% tokens) %>%
    filter(target != word) %>%
  mutate(co_occur = count/sum(count, na.rm = T))

ggplot(direct_co_occurs, aes(x = max_row, y= co_occur, color = word)) + 
  facet_wrap(~target) + 
  geom_line() 
 # scale_y_continuous(limits = c(0, .3))




 # scale_y_continuous(limits = c(0, .3))




```
